### ISSUE TITLE
Change docs to conceptualize proof aggregation slightly differently

### ISSUE THREAD

**Issue by hdevalence** [dalek-cryptography/bulletproofs#100]
Note from a discussion with @cathieyun @oleganza about aggregation of circuit proofs (cf #97):

The existing documentation describes aggregation for rangeproofs as multiple parties who want to produce a joint proof that each of their values is in range. This is correct, but it obscures a distinction that's useful in the circuit context.

In fact each of the provers is working independently to produce a proof of *their* statement (that their value is in range), and the dealer is aggregating these statements into a proof that each party's statement holds. But no two parties collaborate to produce a joint proof of a single statement. Because each of the parties is proving the same range statement, this distinction isn't really important in the rangeproof setting.

However, in the circuit setting, it does matter: the distinction is between

1. having each party prove satisfiability of their own circuit (the circuits could possibly be distinct, as long as there's some higher-level way to signal to the verifier which circuits are being proved in which part of the proof);

2. having parties collaborate to prove satisfiability of a single circuit without having to reveal secrets to each other.

For the first one, we can use basically the same framework that we already have to produce an aggregated proof of `m` parties. For the second, we would need a different aggregation framework.
(Why is the second one useful? Because it allows, e.g., proving mixes between parties that don't trust each other.)

When we have notes on circuit proving, we should change the existing rangeproof notes to clarify this distinction.

**Comment by oleganza** [comment]
Addressing this in #191.
