### ISSUE TITLE
Add a `Commitment` struct

### ISSUE THREAD

**Issue by cathieyun** [dalek-cryptography/bulletproofs#144]
`Commitment` that is an enum of `Open(Scalar, Scalar)` and `Closed(RistrettoPoint)` would be a nice addition to working with Pedersen commitments. It could have a `close(PedersenGenerators)` function that generates the RistrettoPoint commitment. 

(see `r1cs-commitments` branch for my first pass at doing this)

**Comment by oleganza** [comment]
Is this a similar issue to #85?

**Comment by cathieyun** [comment]
yes! we can delete this issue, I didn't realize there was already an issue for this
