### ISSUE TITLE
Constraint system code should zero its heap allocations.

### ISSUE THREAD

**Issue by hdevalence** [dalek-cryptography/bulletproofs#146]
This probably isn't worth doing until we're mostly finished writing the constraint system code, but we should do it before we finish it.

**Comment by oleganza** [comment]
Related issue for rangeproofs: https://github.com/dalek-cryptography/bulletproofs/issues/171 and its PR: #183.

Seems like, if/when 
https://github.com/dalek-cryptography/curve25519-dalek/pull/202 is merged upstream, it would be pretty easy to add zeroeing to the vectors of scalars for CS like it's done for RP.

**Comment by oleganza** [comment]
Done in PR #193.

**Comment by oleganza** [comment]
Follow-up discussion about secrets on the stack: #195

**Comment by hdevalence** [comment]
I'm not sure how far we want to go with stack handling and how effective it would really be... First, the stack zeroing should happen at the outermost layer of crypto code, but since the Bulletproofs library is probably going to be used to build protocols, the callers of our functions probably have secrets too.  Second, we don't actually have control over stack allocations.  Third, zeroing data doesn't really correspond to a system security boundary (like process separation) so I'm not sure that it's really reliable for its goals even if it's done "correctly".
