### ISSUE TITLE
Split constraint system logic into prover/verifier types with a common trait

### ISSUE THREAD

**Issue by hdevalence** [dalek-cryptography/bulletproofs#149]
Instead of having a single `ConstraintSystem` type, we should experiment with having

```rust

trait ConstraintSystem;

struct ProverCS;
struct VerifierCS;

impl ConstraintSystem for ProverCS {};
impl ConstraintSystem for VerifierCS {};
```

so that it's clear which code is supposed to abstract over both roles (e.g., gadgets) and which code is supposed to only prove or verify (so it's impossible to call verify on a prover, for instance).

**Comment by cathieyun** [comment]
Closed by https://github.com/dalek-cryptography/bulletproofs/pull/151
