### ISSUE TITLE
Generators should be changed to have a notion of capacity

### ISSUE THREAD

**Issue by hdevalence** [dalek-cryptography/bulletproofs#150]
For circuit proofs, we stream constraints into the constraint system, so it's not known in advance how many generators we're going to need. The current `Generators` struct has a fixed number of generators for each party, and the code checks that this is equal to the number of generators needed.

However, since we already changed the `Generators` struct to generate each aggregation party's generators using a different, domain separated XOF, we can view each party's share in the `Generators` struct as the leading slice of an arbitrarily-long chain of independent generators.

This gives a nice way to solve the problem for the constraint system: we can change the `Generators` struct to have a notion of a `capacity` (the length of the slice), construct `capacity` many generators for each party on initialization, and have all of the proving methods check that the number of generators they need is less than the capacity (or else return an error). 

Checklist:

- [x] Add a notion of `capacity` to the `Generators` struct
- [x] Change the rangeproof code to be capacity-aware
- [x] Merge those changes into `main`
- [x] Merge `main` into `circuit` and update the circuit code to be capacity-aware.

**Comment by hdevalence** [comment]
The first three points are done by #152

**Comment by cathieyun** [comment]
Last point is done by https://github.com/dalek-cryptography/bulletproofs/pull/153, so I'm closing this issue
