### ISSUE TITLE
Constraint systems should hold onto a Generators object

### ISSUE THREAD

**Issue by hdevalence** [dalek-cryptography/bulletproofs#155]
I think it might be cleaner to pass in borrows of everything the constraint systems will need to prove and verify up front, so that the final `prove` / `verify` calls just consume the CS and don't need any further parameters.

**Comment by cathieyun** [comment]
Can we generate a rng from the transcript in the `verifier_cs` the same way we do in the `prover_cs`?

**Comment by hdevalence** [comment]
It's not unsafe -- since the `TranscriptRng` is a PRF, it shouldn't be possible for the prover to predict what the verifier's randomness will be (and use that to come up with a malicious transcript), but because the randomness isn't as critical (it's just used to combine statements, so it can't leak any secrets) I think that it would be fine for the verifier to just call `thread_rng` internally.

**Comment by cathieyun** [comment]
Okay, in that case I'll have the verifier make their own `TranscriptRng` for randomness! Then we'll have a really nice API where you just call `.prove()` or `.verify(proof)`, and don't have to pass in anything else :)

**Comment by cathieyun** [comment]
closed by https://github.com/dalek-cryptography/bulletproofs/pull/158
