### ISSUE TITLE
Eliminate padding variables

### ISSUE THREAD

**Issue by hdevalence** [dalek-cryptography/bulletproofs#156]
Right now the constraint systems pad to the nearest power of 2 by adding dummy multipliers. But instead we could change the proving and verification logic to pad with zeros, which would reduce the cost of proving and verification.

**Comment by oleganza** [comment]
Might be a good idea to start by updating the prover's and verifier's protocols write-up to assume non-power-of-two vectors (including IPP) and explicitly show how and why we can do padding at the lowest level. E.g. when we split two vectors in two halves and combine with them with a challenge, or when we flatten the weights etc.

**Comment by oleganza** [comment]
I'd like to fix this after the #184 and #159 are merged.

We do not require n = power-of-2 in the build up towards the inner product proof. This means we can explicitly specify how vectors `l(x)` and `r(x)` get padded to a next power of two with zeroes, which is equivalent to padding the CS with zero multipliers, zero weights and zero blinding factors `s_{L,R}`. 

Once we have justified padding IPP inputs with zeroes, we can eliminate explicit padding and asserts inside IPP implementation. For instance, we can have a version of `inner_product` function that folds left/right "halves" of a vector, truncating the longer one as it's equivalent to multiplying it by an all-zero tail from another "half" (virtually padded with zeroes).

**Comment by oleganza** [comment]
Actually, scratch that. In IPP we also need power-of-two generators, to compute cross-terms correctly, so it's probably not going to save us performance if we try to virtually pad vectors of scalars.

As Henry said above, we can simply pad l(x) and r(x) with zeroes (after proper justification) and let IPP work as it is now, but removing the padding from the higher-level.

**Comment by oleganza** [comment]
PR: https://github.com/dalek-cryptography/bulletproofs/pull/190
