### ISSUE TITLE
Update aggregated proof protocol diagram

### ISSUE THREAD

**Issue by hdevalence** [dalek-cryptography/bulletproofs#174]
Since `ValueCommitment` was renamed to `BitCommitment`, the SVG is out of date and needs to be updated (cf #169)

**Comment by oleganza** [comment]
Done here, pending review: https://github.com/dalek-cryptography/bulletproofs/pull/175

**Comment by hdevalence** [comment]
Looks like there's an issue with SVG escaping, maybe https://stackoverflow.com/questions/30676125/svg-as-data-uri-triggers-xml-parsing-error-in-firefox is relevant?

**Comment by oleganza** [comment]
Indeed. Thanks.

**Comment by hdevalence** [comment]
Closed by #175
