### ISSUE TITLE
R1CS benchmark

### ISSUE THREAD

**Issue by hdevalence** [dalek-cryptography/bulletproofs#180]
We should probably have at least one benchmark.  The benchmarks are totally dependent on the circuit, so if we have a shuffle circuit in the doctests anyways (#179), we might want to use it as a benchmark.  The current benchmarks are in `benches/bulletproofs.rs`; I think this should probably be renamed to `benches/rangeproof.rs` and the R1CS benchmarks can go in `benches/r1cs.rs`.

**Comment by cathieyun** [comment]
PR for shuffle benchmark here: https://github.com/dalek-cryptography/bulletproofs/pull/187

**Comment by cathieyun** [comment]
we merged the kshuffle benchmark into the `circuit` branch, so can we close this issue? Or would we like to add more benchmarks? @hdevalence
