### ISSUE TITLE
Why does PedersonGens::default().B and .B_blinding return four Edward's points?

### ISSUE THREAD

**Issue by Dylan-Phoon** [dalek-cryptography/bulletproofs#205]
Why are four different edward's points returned for B and B_blinding? Wouldnt one point be just fine?

<img width="835" alt="screenshot 2018-11-08 at 06 25 26" src="https://user-images.githubusercontent.com/37438950/48181432-5a1ad780-e31f-11e8-9e2a-8976e831b7af.png">

**Comment by oleganza** [comment]
Can you share a piece of code that produces this output? Pedersen commitments require a pair of points, so there are two: `B` and `B_blinding`.

**Comment by hdevalence** [comment]
What you're looking at is the `Debug` display of a `RistrettoPoint`. 

Ristretto constructs a quotient group, so each element of the Ristretto group is represented by a single Edwards point. However, this representation is not unique: there are four possible representatives, and the `Debug` display computes and displays all of them.  The top line, partially cropped out of the screenshot, that says "RistrettoPoint: [coset](https://en.wikipedia.org/wiki/Coset) ...", is supposed to mean that the next four points are the representatives of the `RistrettoPoint`.
