### ISSUE TITLE
API for allocating one low-level variable at a time

### ISSUE THREAD

**Issue by oleganza** [dalek-cryptography/bulletproofs#206]
Currently the API `assign_uncommitted` exposes a whole multiplier, returning two variables: left and right wire. If the user needs only one, they can discard the other. This is slightly suboptimal and looks like a leaky abstraction: in a loop over K gadgets that are connected with K-1 "wires", the user is faced with a dilemma — try to unroll the loop in pairs to avoid throwing out half of variables, or ignore them?

The suggestion is:

1. The API always returns one variable at a time.
2. If there is no half-assigned multiplier: CS allocates a new one, assigns and returns the left wire, assigns 0 to the unused right wire and keeps track of the multiplier till the next call, or till the CS is committed.
3. When the next call comes in, the remembered multiplier's right wire is assigned, output wire is recalculated, right wire is returned to the user, and CS forgets about that multiplier.
4. When CS is committed, if there is a half-assigned multiplier hanging on, CS "forgets" it and keeps its zero-assignments to the right and output wire.

This way, each odd call creates a new multiplier and each even call completes the assignment of the already existing multiplier. If CS has to allocate the normal multiplier in the middle, it does not conflict with the half-assigned multiplier because it would have its own index in the array from the beginning.

This change should be pretty small in its complexity. I don't think it is a meaningful performance win, but the API should be more clean this way.

PS. Per https://github.com/dalek-cryptography/bulletproofs/issues/186, first-phase variables are no longer "uncommitted" and can very well be committed. So we should find a more appropriate name, e.g. "assign_internal_variable" or something like that.

PR: #256

**Comment by hdevalence** [comment]
Let's re-triage this after #222

**Comment by oleganza** [comment]
Here's an example of current `allocate` usage when only one variable is needed:
https://github.com/interstellar/slingshot/blob/main/zkvm/src/vm.rs#L463-L475

```rust
        let (neg_qty_var, _, _) = cs.allocate(|| {
                Ok((
                    -(qty_assignment
                        .ok_or(R1CSError::MissingAssignment)?
                        .to_scalar()),
                    Scalar::zero(),
                    Scalar::zero(),
                ))
            })?;
```

ideally it should instead look like

```rust
        let neg_qty_var = cs.allocate(|| {
                Ok(
                    -(qty_assignment
                        .ok_or(R1CSError::MissingAssignment)?
                        .to_scalar()),
                )
            })?;
```

**Comment by cathieyun** [comment]
Given that #256 is merged, let's close this issue!
