### ISSUE TITLE
Publish 1.0 crate

### ISSUE THREAD

**Issue by hdevalence** [dalek-cryptography/bulletproofs#234]
This can be done now that #137 is merged into `develop`.

I don't feel super comfortable publishing the R1CS code yet, even behind the `yoloproofs` feature, so I'm wondering about commenting out the `yoloproofs` feature in the `Cargo.toml` before releasing `1.0`. This way, the `crates.io` version has the R1CS code permanently disabled, and the only way to use the R1CS api is by adding a git dependency on the `develop` branch to a downstream project.  This prevents someone from publishing a crate that uses the unfinished R1CS code.

WDYT @cathieyun @oleganza ?

**Comment by oleganza** [comment]
Sounds fine with me.

**Comment by hdevalence** [comment]
This is done!
