### ISSUE TITLE
R1CS : Prove I know input to sha256

### ISSUE THREAD

**Issue by GoldiLocksMiller** [dalek-cryptography/bulletproofs#245]
How to prove I know input to sha256 using your r1cs?

**Comment by oleganza** [comment]
You have to write a "sha256 gadget" that creates constraints between an preimage bitstring and an image bitstring. Lets say your image is public, preimage is secret, and the bitlength of the preimage is public. You can programmatically generate constraints for the given image and input bitlength. Preimage probably makes sense to break into 32-bit limbs and commit to each of them using Pedersen commitments.

See https://github.com/interstellar/spacesuit for an example of how to build gadgets and compose them.

**Comment by GoldiLocksMiller** [comment]
@oleganza Thank you. Do you have many more simple examples?

Like how to check that secret value is > X ?

**Comment by oleganza** [comment]
First, you need to get to integers from scalars because scalars are _going circles_ mod group order and  comparison does not make sense for them. So let's say, secret Y is u64 and X is u64. Then:

1. You add a 64-bit range proof for Y to make sure it's a 64-bit integer.
2. You rewrite `Y > X` as `Y - X > 0`.
3. You add a 64-bit range proof for linear combination `Y-X` to make sure it is a positive integer.

**Comment by GoldiLocksMiller** [comment]
ok i got it. thank you

**Comment by decentralisedkev** [comment]
@oleganza Can this be done without an circuit for sha256?

**Comment by oleganza** [comment]
what do you mean by "this"? if you need to prove that `y = sha256(x)` you need constraints that are equivalent to sha256 computation.

**Comment by decentralisedkev** [comment]
> what do you mean by "this"? if you need to prove that `y = sha256(x)` you need constraints that are equivalent to sha256 computation.

I updated my comment, and yes you are right. Are there any gadgets already out there that implement this already or examples of hashing?

**Comment by oleganza** [comment]
We have tinkered with SHA256-in-bulletproofs and here are some findings: https://dalek-cryptography.slack.com/archives/CBKMRC8DN/p1548181481047300

<img width="787" alt="image" src="https://user-images.githubusercontent.com/698/51558093-749b2200-1e33-11e9-90cc-69e1109f23b5.png">
