### ISSUE TITLE
Add build instructions to the README

### ISSUE THREAD

**Issue by greyspectrum** [dalek-cryptography/bulletproofs#260]
In the course of getting started, I noticed that bulletproofs won't compile with stable Rust, but instead requires nightly Rust. Although the compiler was informative enough that I was able to figure it out, it would likely make it easier for other prospective contributors if this were in the README. I opened a PR [#259](https://github.com/dalek-cryptography/bulletproofs/pull/259).

**Comment by hdevalence** [comment]
Thanks! Created #262 to track stable Rust support & edition changes.
