### ISSUE TITLE
Many of the Notes files contain Raw Latex primitives

### ISSUE THREAD

**Issue by donal-omahony** [dalek-cryptography/bulletproofs#273]
The notes on Rangeproofs and a few other places seem to contain raw Latex primitives which are not rendering properly when the project is viewed through the github website.
e.g.

\[ \mathbf{W}_L \cdot \mathbf{a}_L + \mathbf{W}_R \cdot \mathbf{a}_R + \mathbf{W}_O \cdot \mathbf{a}_O = \mathbf{W}_V \cdot \mathbf{v} + \mathbf{c}, \] where:

**Comment by hdevalence** [comment]
Yup!

Unfortunately there doesn't seem to be a way to get Github to render math -- the way the JS rendering was enabled on docs.rs was via a stored XSS that @isislovecruft found but fortunately/unfortunately this isn't possible on github.com.  

You can see the formulas rendered at: [doc.dalek.rs/bulletproofs](https://doc.dalek.rs/bulletproofs) and [doc-internal.dalek.rs/bulletproofs](https://doc-internal.dalek.rs/bulletproofs)
