### ISSUE TITLE
Pedersen Commitment Division

### ISSUE THREAD

**Issue by arthurgreef** [dalek-cryptography/bulletproofs#281]
Hi - the following link is a protocol for sealed bid auctions. The protocol divides one pedersen commitment by another. It is not obvious to me if the pedersen commitment API supports this division operator. Am I missing something? Thanks.

https://medium.com/@vaheandonians/publicly-verifiable-sealed-bid-auctions-with-a-trustless-auctioneer-4aa50197f00c

**Comment by decentralisedkev** [comment]
Hi, 

The article uses multiplicative notation when dividing B_i by B_j, division of two points can be seen as subtraction using additive notation
