### ISSUE TITLE
Incorrect path for doc include range proof

### ISSUE THREAD

**Issue by vlopes11** [dalek-cryptography/bulletproofs#283]
Seems I'm having some problems to evaluate the path for the doc includes with the latest Rust.

```
error: couldn't read src/range_proof/../docs/range-proof-protocol.md: No such file or directory (os error 2)
 --> src/range_proof/mod.rs:2:18
  |
2 | #![doc(include = "../docs/range-proof-protocol.md")]
  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ couldn't read file
```

The absolute path should consider one more level. Here is a pull request that fixes it.
https://github.com/dalek-cryptography/bulletproofs/pull/282

**Comment by hdevalence** [comment]
Thanks for spotting this -- I think that there might have been a change to doc import paths.  Right now we're in a bit of a weird state because the travis config is using an outdated nightly, so I'll circle back to this after updating it.

**Comment by hdevalence** [comment]
https://rust-lang.github.io/rustup-components-history/ suggests that all of the components we like (rls, fmt, etc) are available as of today's nightly, let's try upgrading.

**Comment by vlopes11** [comment]
Tested and fixed. I'll close the PR + this issue.

Thanks!
