### ISSUE TITLE
What tool do you use to describe the encryption algorithm circuit???

### ISSUE THREAD

**Issue by amazingMan2017** [dalek-cryptography/bulletproofs#304]
What tool do you use to describe the encryption algorithm circuit of bulletproofs in repository 
https://github.com/dalek-cryptography/bulletproofs ??

**Comment by WildCryptoFox** [comment]
This colourful thing? It is just edited screenshots of papers. You could use LaTeX to do this too.

![](https://camo.githubusercontent.com/a802898b14396e11627285c5f231e653b0a35a22/68747470733a2f2f646f632e64616c656b2e72732f6173736574732f62756c6c657470726f6f66732d72616e676570726f6f662e706e67)

**Comment by hdevalence** [comment]
That diagram was all @oleganza's work :)

**Comment by amazingMan2017** [comment]
well, this diagram looks so cool , anything else besides Latex??

**Comment by oleganza** [comment]
@amazingMan2017 it's copy-pasted formulas from KaTeX documentation into OS X Keynote presentation.

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/698/69940471-ae709680-14e2-11ea-9f18-2c6fb745b8cf.png">

**Comment by hdevalence** [comment]
Going to close this out because it seems to have been answered :)
