### ISSUE TITLE
is bulletproofs supported in no_std environment?

### ISSUE THREAD

**Issue by mikedoan** [dalek-cryptography/bulletproofs#312]
I believe this code is not fully supported in no_std environment but i need to get the confirmation from the author? I did not manage to send an email to you (https://dalek.rs) it seems like your email is not reachable

**Comment by hdevalence** [comment]
Yup, there's no email, just Github issues. A third-party contributor added `no_std` support, and it seemed to work at the time, but it hasn't been a maintenance priority, so it very well could have broken. If something's not working for you, please file a detailed issue with a description of what went wrong :smiley:
