### ISSUE TITLE
Proofs merging

### ISSUE THREAD

**Issue by zie1ony** [dalek-cryptography/bulletproofs#315]
I have two pairs: `(proof_a, commit_a)` and `(proof_b, commit_b)`.
Is it possible to merge `proof_a` and `proof_b` so it proofs `commit_a + commit_b`?

**Comment by oleganza** [comment]
If you have `C=Com(a+b)` and want to prove that it is equal to `A=Com(a)` and `B=Com(b)`, then you can simply choose the blinding factors for C as sum of blinding factors for A and B and check `C == A + B`.

**Comment by zie1ony** [comment]
In my example I work with Pedersen Commitments, so: `commit = value * G + blinding * H` and `proof` should proof that `0 =< value =< max`.
I don't have blindings known. In the best case I can construct `(proof_b, commit_b)` knowing `(proof_a, commit_a)`, so I would know `blinding_b`, but I don't know how is that helping here.

**Comment by zie1ony** [comment]
Looks like it's not possible.
