### ISSUE TITLE
Pedersen commitment structure

### ISSUE THREAD

**Issue by oleganza** [dalek-cryptography/bulletproofs#85]
It seems like we can benefit from grouping together value, blinding factor and generators in a single struct. Lets call it `OpenCommitment` (or `DeferredCommitment`, or something like that).

Benefits:

1. We can pass a single list of such commitments instead of a two lists - with values and with blinding factors.
2. We can pass pedersen generators within such structs instead of passing them inside GeneratorsView, which may help us simplify the API of the latter.

WDYT?

**Comment by hdevalence** [comment]
Closing as stale per @oleganza
